name: Build

on:
  push:
  pull_request:

jobs:
  btp:
    name: Build-Tag-Push
    runs-on: ubuntu-latest

    env:
      PUBLIC_IMAGE_PREFIX: 'datastewardshipwizard'
      DOCKER_IMAGE_NAME: 'fip-version-project-action'
      DOCKER_META_CONTEXT: '.'
      DOCKER_META_FILE: 'Dockerfile'
      DOCKER_META_PLATFORMS: 'linux/amd64,linux/arm64'

    steps:
    - name: '[setup] Check out repository'
      uses: actions/checkout@v5

    - name: '[setup] Set up QEMU'
      uses: docker/setup-qemu-action@v3

    - name: '[setup] Set up Docker Buildx'
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: '[docker] Docker meta'
      id: meta-test
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.PUBLIC_IMAGE_PREFIX }}/${{ env.DOCKER_IMAGE_NAME }}
        tags: |
          type=sha

    - name: '[docker] Docker build'
      uses: docker/build-push-action@v6
      with:
        context: ${{ env.DOCKER_META_CONTEXT }}
        file: ${{ env.DOCKER_META_FILE }}
        platforms: ${{ env.DOCKER_META_PLATFORMS }}
        push: false
        tags: ${{ steps.meta-test.outputs.tags }}
        labels: ${{ steps.meta-test.outputs.labels }}
